feat: Added market data end points for v2 trading data service
vegaprotocol/protos pull request #302
Opened 2022-02-22 12:43 UTC by guoguojin

Closes #301

2022-02-22 12:52 UTC, jeremyletang requested changes
Could we simplify this by having a single rpc method, which takes optional parameters? all of these looks like combination / excluded filter from the others.

I'm not sure I see the point of GetMarketsData as well.

I'd have basically a single GetMarketData rpc, with these filters:
- ID (required)
- From (optional)
- To (optional)
if From and To are not specified, return the last insert

2022-02-22 14:09 UTC, guoguojin commented
The GetMarketsData is something that has been duplicated from the existing API, happy to remove it if you don't think you need it.

2022-02-22 14:46 UTC, jeremyletang commented
> The GetMarketsData is something that has been duplicated from the existing API, happy to remove it if you don't think you need it.

Yea I'm not sure it's really of uses to be fair, I'd guess you would get the list of markets at first, then get the data for the market you wish

2022-02-23 18:22 UTC, pscott31 approved these changes

2022-02-24 09:39 UTC, merged